import { useEffect, useState } from "react";
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { AppIcon, AppText, Field, PrimaryButton, palette } from "@/src/components/ui";
import { useStockTrack } from "@/src/providers/stocktrack-provider";

export default function AuthScreen() {
  const { user, signIn, signUp } = useStockTrack(); const [mode, setMode] = useState<"signIn" | "signUp">("signIn"); const [fullName, setFullName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  useEffect(() => { if (user) router.replace("/stores" as never); }, [user]);
  const submit = async () => { setError(null); setNotice(null); if (mode === "signUp" && fullName.trim().length < 2) return setError("Enter your full name."); if (!email.includes("@")) return setError("Enter a valid email address."); if (password.length < 6) return setError("Password must be at least six characters."); setLoading(true); try { if (mode === "signIn") await signIn(email, password); else { const result = await signUp(fullName, email, password); if (result.requiresConfirmation) setNotice("Check your email to confirm your account, then return to sign in."); } } catch (authError) { setError(authError instanceof Error ? authError.message : "Authentication could not be completed."); } finally { setLoading(false); } };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="p-5"><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={{ flex: 1 }}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.brandMark}><AppIcon name="inventory-2" size={32} color={palette.paper} /></View><View style={{ gap: 5 }}><AppText size={31} weight="700">StockTrack</AppText><AppText size={16} color={palette.slate}>Inventory intelligence for modern teams.</AppText></View><View style={styles.form}><View style={styles.switcher}><PrimaryButton label="Sign in" secondary={mode !== "signIn"} onPress={() => { setMode("signIn"); setError(null); }} /><PrimaryButton label="Create account" secondary={mode !== "signUp"} onPress={() => { setMode("signUp"); setError(null); }} /></View>{mode === "signUp" ? <Field label="Full name" value={fullName} onChangeText={setFullName} autoCapitalize="words" placeholder="Alex Morgan" /> : null}<Field label="Email address" value={email} onChangeText={setEmail} autoCapitalize="none" autoCorrect={false} keyboardType="email-address" placeholder="you@company.com" /><Field label="Password" value={password} onChangeText={setPassword} secureTextEntry={!showPassword} placeholder="At least 6 characters" /><View style={{ alignSelf: "flex-end" }}><PrimaryButton label={showPassword ? "Hide password" : "Show password"} secondary onPress={() => setShowPassword((value) => !value)} /></View>{error ? <View style={styles.error}><AppIcon name="error-outline" size={18} color={palette.red} /><AppText size={13} color={palette.red}>{error}</AppText></View> : null}{notice ? <View style={styles.notice}><AppIcon name="mark-email-read" size={18} color={palette.green} /><AppText size={13} color={palette.green}>{notice}</AppText></View> : null}<PrimaryButton label={mode === "signIn" ? "Sign in to StockTrack" : "Create secure account"} loading={loading} onPress={() => void submit()} icon={mode === "signIn" ? "login" : "person-add"} /></View><AppText size={12} color={palette.slate} style={{ textAlign: "center" }}>Your store data is protected by server-side membership rules. Offline updates stay on this device until they can safely sync.</AppText></ScrollView></KeyboardAvoidingView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { flexGrow: 1, justifyContent: "center", gap: 25, paddingVertical: 20 }, brandMark: { height: 68, width: 68, borderRadius: 22, backgroundColor: palette.indigo, alignItems: "center", justifyContent: "center", shadowColor: palette.indigo, shadowOpacity: 0.2, shadowRadius: 10, elevation: 4 }, form: { gap: 15, marginTop: 8 }, switcher: { flexDirection: "row", gap: 8 }, error: { backgroundColor: "#FDECEC", borderRadius: 12, padding: 12, flexDirection: "row", gap: 8, alignItems: "center" }, notice: { backgroundColor: "#E9F7F0", borderRadius: 12, padding: 12, flexDirection: "row", gap: 8, alignItems: "center" } });
