import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { AppIcon, AppText, Card, EmptyState, IconButton, PrimaryButton, ScreenTitle, palette } from "@/src/components/ui";
import { formatQuantity, parseQuantity } from "@/src/lib/quantity";
import { createBulkSessionLocally } from "@/src/data/sync/mutations";
import { useRole, useStockTrack } from "@/src/providers/stocktrack-provider";

export default function BulkSessionScreen() { const { type: rawType } = useLocalSearchParams<{ type?: "IN" | "OUT" }>(); const type = rawType === "OUT" ? "OUT" : "IN"; const { activeStore, data, user, refreshLocal } = useStockTrack(); const role = useRole(); const [selected, setSelected] = useState<Record<string, string>>({}); const [search, setSearch] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const items = useMemo(() => data.items.filter((item) => `${item.name} ${item.barcode ?? ""} ${item.categoryName}`.toLowerCase().includes(search.toLowerCase())), [data.items, search]); const chosen = data.items.filter((item) => selected[item.id] !== undefined); const color = type === "IN" ? palette.green : palette.red;
  if (!activeStore || !user || !role) return <ScreenContainer className="p-5"><EmptyState icon="storefront" title="Choose a store first" body="A stock session belongs to one selected store." /></ScreenContainer>;
  const toggle = (id: string) => setSelected((current) => current[id] === undefined ? { ...current, [id]: "1" } : Object.fromEntries(Object.entries(current).filter(([key]) => key !== id)));
  const submit = async () => { const lines = chosen.map((item) => ({ item, quantityHundredths: parseQuantity(selected[item.id]) ?? 0 })); if (!lines.length || lines.some((line) => line.quantityHundredths <= 0)) return setError("Select at least one item and enter a positive quantity for every selected line."); setBusy(true); setError(null); try { const session = await createBulkSessionLocally(activeStore.id, type, lines, { id: user.id, name: String(user.user_metadata.full_name ?? user.email ?? "You"), role }); await refreshLocal(); router.replace({ pathname: "/session-detail" as never, params: { id: session.id } }); } catch (sessionError) { setError(sessionError instanceof Error ? sessionError.message : "Bulk session could not be recorded."); } finally { setBusy(false); } };
  const header = <><ScreenTitle title={type === "IN" ? "Bulk stock in" : "Bulk stock out"} subtitle={`${activeStore.name} · ${chosen.length} selected`} action={<IconButton icon="close" label="Close" onPress={() => router.back()} />} /><View style={[styles.direction, { backgroundColor: `${color}18` }]}><AppIcon name={type === "IN" ? "add-circle" : "remove-circle"} size={20} color={color} /><AppText size={13} weight="700" color={color}>Every line will be applied as one atomic session.</AppText></View>{chosen.length ? <Card><AppText size={15} weight="700">Selected items</AppText>{chosen.map((item) => <View key={item.id} style={styles.selectedLine}><View style={{ flex: 1 }}><AppText size={14} weight="600">{item.name}</AppText><AppText size={12} color={palette.slate}>{item.categoryName} · {formatQuantity(item.quantityHundredths)} {item.unit} in stock</AppText></View><TextInput value={selected[item.id]} onChangeText={(value) => setSelected((current) => ({ ...current, [item.id]: value }))} keyboardType="decimal-pad" accessibilityLabel={`Quantity for ${item.name}`} style={styles.quantityInput} /><IconButton icon="close" label={`Remove ${item.name}`} onPress={() => toggle(item.id)} color={palette.red} /></View>)}</Card> : null}<View style={styles.search}><AppIcon name="search" size={20} color={palette.slate} /><TextInput value={search} onChangeText={setSearch} placeholder="Search item, barcode, or category…" placeholderTextColor="#98A2B3" style={{ flex: 1, color: palette.ink, fontSize: 15 }} /></View>{error ? <AppText size={13} color={palette.red}>{error}</AppText> : null}</>;
  return <ScreenContainer className="p-4"><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListHeaderComponent={header} renderItem={({ item }) => <Pressable accessibilityRole="checkbox" accessibilityLabel={`Select ${item.name}`} accessibilityState={{ checked: selected[item.id] !== undefined }} onPress={() => toggle(item.id)} style={({ pressed }) => [styles.itemRow, selected[item.id] !== undefined && { borderColor: color, backgroundColor: `${color}09` }, pressed && { opacity: 0.7 }]}><View style={[styles.checkbox, selected[item.id] !== undefined && { backgroundColor: color, borderColor: color }]}>{selected[item.id] !== undefined ? <AppIcon name="check" size={17} color={palette.paper} /> : null}</View><View style={{ flex: 1, gap: 2 }}><AppText size={15} weight="700">{item.name}</AppText><AppText size={12} color={palette.slate}>{item.categoryName} · {formatQuantity(item.quantityHundredths)} {item.unit}</AppText></View></Pressable>} ListEmptyComponent={<EmptyState icon="inventory-2" title="No inventory items" body="Add inventory before starting a bulk session." />} ListFooterComponent={chosen.length ? <PrimaryButton label={`Apply ${chosen.length} item${chosen.length === 1 ? "" : "s"}`} loading={busy} onPress={() => void submit()} icon="check" /> : undefined} /></ScreenContainer>;
}
const styles = StyleSheet.create({ list: { gap: 10, paddingBottom: 30 }, direction: { padding: 11, borderRadius: 12, flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 4 }, selectedLine: { flexDirection: "row", alignItems: "center", gap: 8, borderTopWidth: 1, borderTopColor: "#F0F2F5", paddingTop: 10 }, quantityInput: { width: 66, minHeight: 42, borderWidth: 1, borderColor: palette.border, borderRadius: 10, paddingHorizontal: 8, color: palette.ink, textAlign: "center" }, search: { height: 48, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.paper, borderRadius: 14, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 8 }, itemRow: { minHeight: 66, padding: 12, gap: 11, flexDirection: "row", alignItems: "center", backgroundColor: palette.paper, borderWidth: 1, borderColor: palette.border, borderRadius: 15 }, checkbox: { width: 25, height: 25, borderRadius: 8, borderWidth: 1.5, borderColor: "#C5CBD8", alignItems: "center", justifyContent: "center" } });
