import { useState } from "react";
import { FlatList, Platform, StyleSheet, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { AppIcon, AppText, Card, EmptyState, IconButton, PrimaryButton, ScreenTitle, palette } from "@/src/components/ui";
import { parseInventoryCsv, type ImportIssue, type ParsedImportRow } from "@/src/features/inventory/csv";
import { importInventoryRows } from "@/src/features/inventory/import-service";
import { useRole, useStockTrack } from "@/src/providers/stocktrack-provider";

type ImportSummary = { created: number; updated: number };
export default function CsvImportScreen() { const { activeStore, user, refreshLocal } = useStockTrack(); const role = useRole(); const [rows, setRows] = useState<ParsedImportRow[]>([]); const [issues, setIssues] = useState<ImportIssue[]>([]); const [fileName, setFileName] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [summary, setSummary] = useState<ImportSummary | null>(null); const [error, setError] = useState<string | null>(null); const permitted = role === "owner" || role === "manager";
  const pick = async () => { setError(null); setSummary(null); try { const result = await DocumentPicker.getDocumentAsync({ type: ["text/csv", "text/comma-separated-values", "application/csv"], copyToCacheDirectory: true }); if (result.canceled) return; const asset = result.assets[0]; const text = Platform.OS === "web" && asset.file ? await asset.file.text() : await FileSystem.readAsStringAsync(asset.uri, { encoding: FileSystem.EncodingType.UTF8 }); const parsed = parseInventoryCsv(text); setRows(parsed.validRows); setIssues(parsed.issues); setFileName(asset.name); } catch (pickError) { setError(pickError instanceof Error ? pickError.message : "The CSV could not be read."); } };
  const apply = async () => { if (!activeStore || !user || !role || !rows.length) return; setBusy(true); setError(null); try { const result = await importInventoryRows(activeStore.id, { id: user.id, name: String(user.user_metadata.full_name ?? user.email ?? "You"), role }, rows); await refreshLocal(); setSummary(result); } catch (importError) { setError(importError instanceof Error ? importError.message : "The import could not be recorded."); } finally { setBusy(false); } };
  if (!permitted) return <ScreenContainer className="p-5"><EmptyState icon="lock" title="Manager access required" body="Only managers and owners can import inventory from CSV." /></ScreenContainer>;
  const preview = [...rows.map((row) => ({ key: `valid-${row.rowNumber}`, kind: "valid" as const, row })), ...issues.map((issue) => ({ key: `issue-${issue.rowNumber}-${issue.reason}`, kind: "issue" as const, issue }))];
  return <ScreenContainer className="p-4"><FlatList data={preview} keyExtractor={(item) => item.key} contentContainerStyle={styles.list} ListHeaderComponent={<><ScreenTitle title="CSV import" subtitle={activeStore?.name ?? "Choose a store"} action={<IconButton icon="close" label="Close" onPress={() => router.back()} />} /><Card><AppText size={16} weight="700">Import inventory rows</AppText><AppText size={13} color={palette.slate}>Accepted headers: item_name/name/item, quantity/qty/stock, and optional category/cat. Valid rows import even when others need correction.</AppText><PrimaryButton label={fileName ? "Choose another CSV" : "Choose CSV file"} icon="upload-file" onPress={() => void pick()} /></Card>{fileName ? <Card><AppText size={14} weight="700">{fileName}</AppText><AppText size={13} color={palette.slate}>{rows.length} valid row{rows.length === 1 ? "" : "s"} · {issues.length} issue{issues.length === 1 ? "" : "s"}</AppText></Card> : null}{summary ? <Card style={{ backgroundColor: "#E9F7F0", borderColor: "#B8E6CF" }}><AppText size={16} weight="700" color={palette.green}>Import complete</AppText><AppText size={13} color={palette.green}>{summary.created} item{summary.created === 1 ? "" : "s"} created and {summary.updated} updated. Changes are queued safely if this device is offline.</AppText><PrimaryButton label="Back to inventory" onPress={() => router.back()} /></Card> : null}{error ? <Card style={{ backgroundColor: "#FDECEC", borderColor: "#F4B9BD" }}><AppText size={13} color={palette.red}>{error}</AppText></Card> : null}{fileName && rows.length && !summary ? <PrimaryButton label={`Import ${rows.length} valid row${rows.length === 1 ? "" : "s"}`} loading={busy} icon="check" onPress={() => void apply()} /> : null}{preview.length ? <AppText size={12} weight="700" color={palette.slate} style={{ letterSpacing: 0.5 }}>PREVIEW</AppText> : null}</>} renderItem={({ item }) => item.kind === "valid" ? <Card style={styles.preview}><View style={styles.previewIcon}><AppIcon name="check" size={18} color={palette.green} /></View><View style={{ flex: 1 }}><AppText size={14} weight="700">Row {item.row.rowNumber} · {item.row.name}</AppText><AppText size={12} color={palette.slate}>{item.row.quantityHundredths / 100} · {item.row.categoryName ?? "General"}</AppText></View></Card> : <Card style={[styles.preview, { backgroundColor: "#FFF9ED", borderColor: "#F1D297" }]}><View style={[styles.previewIcon, { backgroundColor: "#FFF1D2" }]}><AppIcon name="error-outline" size={18} color={palette.amber} /></View><View style={{ flex: 1 }}><AppText size={14} weight="700">Row {item.issue.rowNumber}</AppText><AppText size={12} color={palette.amber}>{item.issue.reason}</AppText></View></Card>} ListEmptyComponent={<EmptyState icon="upload-file" title="Choose a CSV to begin" body="Review every valid row and row-level issue before changes are imported." />} /></ScreenContainer>;
}
const styles = StyleSheet.create({ list: { gap: 10, paddingBottom: 26 }, preview: { flexDirection: "row", alignItems: "center", gap: 10 }, previewIcon: { width: 36, height: 36, borderRadius: 11, backgroundColor: "#E9F7F0", alignItems: "center", justifyContent: "center" } });
