import { useEffect, useState } from "react";
import { Alert, ScrollView, StyleSheet, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { AppText, Card, EmptyState, Field, IconButton, PrimaryButton, ScreenTitle, palette } from "@/src/components/ui";
import { can } from "@/src/lib/permissions";
import { formatQuantity, parseQuantity } from "@/src/lib/quantity";
import { saveItemDraft } from "@/src/data/local/repository";
import { deleteItemLocally } from "@/src/data/sync/mutations";
import { useRole, useStockTrack } from "@/src/providers/stocktrack-provider";

const units = ["pcs", "kg", "g", "L", "mL", "boxes", "reams", "sets", "bottles", "bags", "pairs", "rolls"];
export default function ItemScreen() { const params = useLocalSearchParams<{ id?: string }>(); const id = Array.isArray(params.id) ? params.id[0] : params.id; const { activeStore, user, data, refreshLocal } = useStockTrack(); const role = useRole(); const existing = data.items.find((item) => item.id === id) ?? null; const [name, setName] = useState(existing?.name ?? ""); const [quantity, setQuantity] = useState(existing ? formatQuantity(existing.quantityHundredths) : "0"); const [threshold, setThreshold] = useState(existing ? formatQuantity(existing.lowStockThresholdHundredths) : "5"); const [categoryId, setCategoryId] = useState(existing?.categoryId ?? data.categories[0]?.id ?? null); const [unit, setUnit] = useState(existing?.unit ?? "pcs"); const [barcode, setBarcode] = useState(existing?.barcode ?? ""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!can(role, "editItems")) router.back(); }, [role]);
  if (!activeStore || !user || !can(role, "editItems")) return <ScreenContainer className="p-5"><EmptyState icon="lock" title="Manager access required" body="You do not have permission to edit inventory items." /></ScreenContainer>;
  const actor = { id: user.id, name: String(user.user_metadata.full_name ?? user.email ?? "You"), role: role ?? "manager" };
  const save = async () => { const initial = parseQuantity(quantity); const lowThreshold = parseQuantity(threshold); const category = data.categories.find((item) => item.id === categoryId); if (name.trim().length < 2 || name.trim().length > 120) return setError("Item name must contain 2–120 characters."); if (initial === null || lowThreshold === null) return setError("Quantities must use no more than two decimal places."); if (barcode && !/^\d+$/.test(barcode)) return setError("Barcode can contain digits only."); setSaving(true); setError(null); try { await saveItemDraft(activeStore.id, actor, { name, categoryId, categoryName: category?.name ?? "General", quantityHundredths: initial, lowStockThresholdHundredths: lowThreshold, unit, barcode: barcode || null }, existing); await refreshLocal(); router.back(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Item could not be saved."); } finally { setSaving(false); } };
  const remove = () => { if (!existing || role !== "owner") return; Alert.alert(`Delete ${existing.name}?`, "This cannot be undone. Any pending offline deletion will sync when you are online.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => { void deleteItemLocally(existing, { ...actor, role: "owner" }).then(refreshLocal).then(() => router.back()).catch((deleteError) => setError(deleteError instanceof Error ? deleteError.message : "Item could not be deleted.")); } }]); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="p-4"><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><ScreenTitle title={existing ? "Edit item" : "Add item"} subtitle={activeStore.name} action={<IconButton icon="close" label="Close" onPress={() => router.back()} />} /><Card><AppText size={16} weight="700">Item details</AppText><Field label="Item name" value={name} onChangeText={setName} placeholder="e.g. A4 copy paper" autoCapitalize="words" />{existing ? <View style={styles.readOnlyQuantity}><AppText size={13} weight="600" color={palette.slate}>Current quantity</AppText><AppText size={16} weight="700">{formatQuantity(existing.quantityHundredths)} {existing.unit}</AppText><AppText size={12} color={palette.slate}>Use Stock In / Stock Out on Inventory to change quantity — it stays audited there.</AppText></View> : <Field label="Initial quantity" value={quantity} onChangeText={setQuantity} placeholder="0" keyboardType="decimal-pad" />}<Field label="Low stock alert threshold" value={threshold} onChangeText={setThreshold} placeholder="5" keyboardType="decimal-pad" /><Field label="Barcode (optional)" value={barcode} onChangeText={setBarcode} placeholder="Digits only" keyboardType="number-pad" /></Card><Card><AppText size={16} weight="700">Category</AppText><View style={styles.choiceWrap}>{data.categories.map((item) => <PrimaryButton key={item.id} label={item.name} secondary={categoryId !== item.id} onPress={() => setCategoryId(item.id)} />)}</View><AppText size={16} weight="700" style={{ marginTop: 6 }}>Unit</AppText><View style={styles.choiceWrap}>{units.map((value) => <PrimaryButton key={value} label={value} secondary={unit !== value} onPress={() => setUnit(value)} />)}</View></Card>{error ? <AppText size={13} color={palette.red}>{error}</AppText> : null}<PrimaryButton label={existing ? "Save changes" : "Create item"} loading={saving} icon="save" onPress={() => void save()} />{existing && role === "owner" ? <PrimaryButton label="Delete item" secondary onPress={remove} icon="delete-outline" /> : null}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { gap: 14, paddingBottom: 24 }, choiceWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, readOnlyQuantity: { gap: 3, backgroundColor: palette.subtle, borderRadius: 13, padding: 12 } });
