import { useEffect, useState } from "react";
import { Alert, FlatList, StyleSheet, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { AppIcon, AppText, Card, EmptyState, IconButton, OutlineButton, PrimaryButton, ScreenTitle, palette } from "@/src/components/ui";
import { formatQuantity } from "@/src/lib/quantity";
import { listSessionItems } from "@/src/data/local/repository";
import { printSessionReport, shareSessionReport } from "@/src/features/sessions/pdf";
import { useStockTrack } from "@/src/providers/stocktrack-provider";
import type { StockSessionItem } from "@/src/lib/types";

export default function SessionDetailScreen() { const { id: rawId } = useLocalSearchParams<{ id?: string }>(); const id = Array.isArray(rawId) ? rawId[0] : rawId; const { activeStore, data } = useStockTrack(); const session = data.sessions.find((candidate) => candidate.id === id); const [lines, setLines] = useState<StockSessionItem[]>([]); const [busy, setBusy] = useState(false); useEffect(() => { if (id) void listSessionItems(id).then(setLines); }, [id]); if (!activeStore || !session) return <ScreenContainer className="p-5"><EmptyState icon="history" title="Session unavailable" body="The session may not be available in this store cache." /></ScreenContainer>; const typeColor = session.sessionType === "IN" ? palette.green : palette.red; const run = async (kind: "share" | "print") => { setBusy(true); try { if (kind === "share") await shareSessionReport(activeStore, session, lines); else await printSessionReport(activeStore, session, lines); } catch (reportError) { Alert.alert("Report unavailable", reportError instanceof Error ? reportError.message : "Try again when report services are available."); } finally { setBusy(false); } };
  return <ScreenContainer className="p-4"><FlatList data={lines} keyExtractor={(line) => line.id} contentContainerStyle={styles.list} ListHeaderComponent={<><ScreenTitle title={session.sessionType === "IN" ? "Stock In Complete" : "Stock Out Complete"} subtitle={activeStore.name} action={<IconButton icon="close" label="Close" onPress={() => router.back()} />} /><Card><View style={styles.sessionHead}><View style={[styles.sessionIcon, { backgroundColor: `${typeColor}18` }]}><AppIcon name={session.sessionType === "IN" ? "add-circle" : "remove-circle"} size={25} color={typeColor} /></View><View><AppText size={17} weight="700">{session.totalItems} successful item{session.totalItems === 1 ? "" : "s"}</AppText><AppText size={13} color={palette.slate}>{session.performerName} · {session.performerRole}</AppText></View></View><AppText size={13} color={palette.slate}>{new Date(session.createdAt).toLocaleString()}</AppText></Card><View style={styles.actions}><View style={{ flex: 1 }}><PrimaryButton label="Share PDF" loading={busy} icon="share" onPress={() => void run("share")} /></View><View style={{ flex: 1 }}><OutlineButton label="Print" icon="print" onPress={() => void run("print")} /></View></View><AppText size={12} weight="700" color={palette.slate} style={{ letterSpacing: 0.6 }}>SESSION LINES</AppText></>} renderItem={({ item }) => <Card style={styles.line}><View style={{ flex: 1 }}><AppText size={15} weight="700">{item.itemName}</AppText><AppText size={12} color={palette.slate}>{item.category}</AppText></View><AppText size={16} weight="700" color={item.quantityHundredths >= 0 ? palette.green : palette.red}>{item.quantityHundredths > 0 ? "+" : ""}{formatQuantity(item.quantityHundredths)} {item.unit}</AppText></Card>} ListEmptyComponent={<EmptyState icon="info-outline" title="Item details unavailable offline" body="This cached session has a summary, but its line items have not been downloaded yet." />} /></ScreenContainer>; }
const styles = StyleSheet.create({ list: { gap: 11, paddingBottom: 25 }, sessionHead: { flexDirection: "row", alignItems: "center", gap: 11 }, sessionIcon: { width: 48, height: 48, borderRadius: 15, justifyContent: "center", alignItems: "center" }, actions: { flexDirection: "row", gap: 10 }, line: { flexDirection: "row", alignItems: "center" } });
