import { useEffect, useState } from "react";
import { Alert, FlatList, StyleSheet, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { AppIcon, AppText, Card, EmptyState, Field, IconButton, PrimaryButton, palette } from "@/src/components/ui";
import { useStockTrack } from "@/src/providers/stocktrack-provider";
import type { Store } from "@/src/lib/types";

export default function StoresScreen() {
  const { user, stores, activeStore, createStore, selectStore, signOut } = useStockTrack(); const [name, setName] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!user) router.replace("/auth" as never); if (activeStore) router.replace("/(tabs)" as never); }, [activeStore, user]);
  const addStore = async () => { setError(null); if (name.trim().length < 2) return setError("Store name must contain at least two characters."); setBusy(true); try { await createStore(name); router.replace("/(tabs)" as never); } catch (createError) { setError(createError instanceof Error ? createError.message : "Could not create the store."); } finally { setBusy(false); } };
  const chooseStore = async (store: Store) => { setBusy(true); try { await selectStore(store.id); router.replace("/(tabs)" as never); } catch (selectionError) { Alert.alert("Store unavailable", selectionError instanceof Error ? selectionError.message : "Could not open that store."); } finally { setBusy(false); } };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="p-5"><View style={styles.header}><View><AppText size={27} weight="700">{stores.length ? "Choose a store" : "Create your first store"}</AppText><AppText size={14} color={palette.slate}>{stores.length ? `${stores.length} store${stores.length === 1 ? "" : "s"} available to you` : "You’ll be the owner of this workspace."}</AppText></View><IconButton icon="logout" label="Sign out" onPress={() => void signOut()} /></View><FlatList data={stores} keyExtractor={(store) => store.id} contentContainerStyle={styles.list} ListEmptyComponent={<EmptyState icon="storefront" title="Ready when you are" body="Create a store to organise stock, collaborate with your team, and work offline." />} renderItem={({ item }) => <Card style={styles.storeCard}><View style={styles.storeIcon}><AppIcon name="storefront" size={23} color={palette.indigo} /></View><View style={{ flex: 1, gap: 2 }}><AppText size={16} weight="700">{item.name}</AppText><AppText size={13} color={palette.slate}>Inventory workspace</AppText></View><PrimaryButton label="Open" secondary onPress={() => void chooseStore(item)} /></Card>} ListFooterComponent={<Card style={{ marginTop: 12, gap: 14 }}><AppText size={16} weight="700">{stores.length ? "Add another store" : "Store details"}</AppText><Field label="Store name" value={name} onChangeText={setName} autoCapitalize="words" placeholder="e.g. Central Warehouse" error={error ?? undefined} /><PrimaryButton label="Create store" loading={busy} icon="add-business" onPress={() => void addStore()} /></Card>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingBottom: 16 }, list: { gap: 12, paddingBottom: 12 }, storeCard: { flexDirection: "row", alignItems: "center" }, storeIcon: { height: 46, width: 46, borderRadius: 14, backgroundColor: "#EEF2FF", alignItems: "center", justifyContent: "center" } });
