import { Platform } from "react-native";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { formatQuantity } from "@/src/lib/quantity";
import type { StockSession, StockSessionItem, Store } from "@/src/lib/types";

const escape = (value: string) => value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);
export function stockSessionReportHtml(store: Store, session: StockSession, lines: StockSessionItem[]): string {
  const title = session.sessionType === "IN" ? "Stock In Report" : "Stock Out Report";
  return `<!doctype html><html><head><meta charset="utf-8" /><style>@page{margin:28px}body{font-family:Helvetica,Arial,sans-serif;color:#172033;font-size:12px}h1{color:#243B78;margin:0 0 4px}h2{margin:3px 0 18px;color:#667085;font-size:15px;font-weight:normal}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:12px;background:#F6F8FC;border-radius:8px;margin-bottom:16px}.label{color:#667085;font-size:10px;text-transform:uppercase}.value{font-weight:bold;font-size:13px;margin-top:2px}table{width:100%;border-collapse:collapse}th{background:#243B78;color:white;text-align:left;padding:8px}td{padding:8px;border-bottom:1px solid #E4E7EC}td:last-child,th:last-child{text-align:right}.in{color:#138A5B}.out{color:#C93E43}</style></head><body><h1>StockTrack</h1><h2>${escape(title)}</h2><div class="grid"><div><div class="label">Store</div><div class="value">${escape(store.name)}</div></div><div><div class="label">Date & time</div><div class="value">${new Date(session.createdAt).toLocaleString()}</div></div><div><div class="label">Performed by</div><div class="value">${escape(session.performerName)} · ${escape(session.performerRole)}</div></div><div><div class="label">Total items</div><div class="value">${session.totalItems}</div></div></div><table><thead><tr><th>Item</th><th>Category</th><th>Quantity</th></tr></thead><tbody>${lines.map((line) => `<tr><td>${escape(line.itemName)}</td><td>${escape(line.category)}</td><td class="${line.quantityHundredths >= 0 ? "in" : "out"}">${line.quantityHundredths > 0 ? "+" : ""}${formatQuantity(line.quantityHundredths)} ${escape(line.unit)}</td></tr>`).join("")}</tbody></table></body></html>`;
}
export async function shareSessionReport(store: Store, session: StockSession, lines: StockSessionItem[]): Promise<void> { if (Platform.OS === "web") { await Print.printAsync({}); return; } const { uri } = await Print.printToFileAsync({ html: stockSessionReportHtml(store, session, lines) }); if (!(await Sharing.isAvailableAsync())) throw new Error("Sharing is not available on this device."); await Sharing.shareAsync(uri, { mimeType: "application/pdf", UTI: ".pdf", dialogTitle: "Share StockTrack report" }); }
export async function printSessionReport(store: Store, session: StockSession, lines: StockSessionItem[]): Promise<void> { await Print.printAsync(Platform.OS === "web" ? {} : { html: stockSessionReportHtml(store, session, lines) }); }
