import { useMemo, useState } from "react";
import { FlatList, StyleSheet, TextInput, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { AppIcon, AppText, Card, EmptyState, IconButton, ScreenTitle, palette } from "@/src/components/ui";
import { canViewActivityAction } from "@/src/lib/permissions";
import { formatQuantity } from "@/src/lib/quantity";
import { useRole, useStockTrack } from "@/src/providers/stocktrack-provider";
import type { ActivityLog } from "@/src/lib/types";

function dateSection(value: string) { const date = new Date(value); const today = new Date(); const yesterday = new Date(Date.now() - 86_400_000); if (date.toDateString() === today.toDateString()) return "Today"; if (date.toDateString() === yesterday.toDateString()) return "Yesterday"; return date.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }); }
function ActivityCard({ log }: { log: ActivityLog }) { const role = useRole(); const isStock = log.actionType === "stock_in" || log.actionType === "stock_out" || log.actionType === "stock_correction"; const color = log.actionType === "stock_in" ? palette.green : log.actionType === "stock_out" ? palette.red : log.actionType === "stock_correction" ? palette.purple : palette.blue; const icon = isStock ? log.actionType === "stock_in" ? "add-circle-outline" : log.actionType === "stock_out" ? "remove-circle-outline" : "edit" : "edit-note"; return <Card style={styles.log}><View style={[styles.logIcon, { backgroundColor: `${color}16` }]}><AppIcon name={icon} size={22} color={color} /></View><View style={{ flex: 1, gap: 2 }}><AppText size={14} weight="700">{isStock ? `${log.actionType === "stock_in" ? "Stock in" : log.actionType === "stock_out" ? "Stock out" : "Owner correction"}${log.itemName ? ` · ${log.itemName}` : ""}` : log.details ?? log.actionType.replace(/_/g, " ")}</AppText><AppText size={12} color={palette.slate}>{log.userName} · {log.userRole} · {new Date(log.createdAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</AppText>{log.details && isStock ? <AppText size={12} color={palette.slate}>{log.details}</AppText> : null}</View>{log.quantityHundredths !== null ? <View style={{ alignItems: "flex-end", gap: 4 }}><AppText size={15} weight="700" color={color}>{formatQuantity(log.quantityHundredths)} {log.unit}</AppText>{role === "owner" && log.itemId && isStock ? <IconButton icon="edit" label={`Correct ${log.itemName ?? "stock"}`} color={palette.purple} onPress={() => router.push({ pathname: "/stock" as never, params: { correctionOf: log.id } })} /> : null}</View> : null}</Card>; }

export default function ActivityScreen() { const { activeStore, data } = useStockTrack(); const role = useRole(); const [query, setQuery] = useState(""); const logs = useMemo(() => data.logs.filter((log) => canViewActivityAction(role, log.actionType)).filter((log) => `${log.itemName ?? ""} ${log.userName} ${log.userRole} ${log.details ?? ""} ${log.actionType}`.toLowerCase().includes(query.toLowerCase())), [data.logs, query, role]); const inCount = logs.filter((log) => log.actionType === "stock_in").length; const outCount = logs.filter((log) => log.actionType === "stock_out").length; const max = Math.max(inCount, outCount, 1);
  if (!role || role === "staff") return <ScreenContainer className="p-5"><EmptyState icon="lock" title="Activity access restricted" body="Managers can review stock actions and owners can review the full audit history." /></ScreenContainer>;
  return <ScreenContainer className="p-4"><FlatList data={logs} keyExtractor={(log) => log.id} contentContainerStyle={styles.list} renderItem={({ item, index }) => <><>{index === 0 || dateSection(item.createdAt) !== dateSection(logs[index - 1].createdAt) ? <AppText size={12} weight="700" color={palette.slate} style={{ letterSpacing: 0.5, marginTop: index ? 6 : 0 }}>{dateSection(item.createdAt).toUpperCase()}</AppText> : null}</><ActivityCard log={item} /></>} ListHeaderComponent={<><ScreenTitle title="Activity" subtitle={activeStore ? `${activeStore.name} · ${role === "owner" ? "Full audit trail" : "Stock actions"}` : "Choose a store"} /><View style={styles.search}><AppIcon name="search" size={21} color={palette.slate} /><TextInput value={query} onChangeText={setQuery} placeholder="Search activity…" placeholderTextColor="#98A2B3" accessibilityLabel="Search activity" style={styles.searchInput} /></View><Card style={styles.chart}><View style={{ flex: 1, gap: 5 }}><AppText size={12} color={palette.slate}>Stock in</AppText><View style={styles.barBackground}><View style={[styles.bar, { width: `${(inCount / max) * 100}%`, backgroundColor: palette.green }]} /></View><AppText size={16} weight="700" color={palette.green}>{inCount}</AppText></View><View style={{ flex: 1, gap: 5 }}><AppText size={12} color={palette.slate}>Stock out</AppText><View style={styles.barBackground}><View style={[styles.bar, { width: `${(outCount / max) * 100}%`, backgroundColor: palette.red }]} /></View><AppText size={16} weight="700" color={palette.red}>{outCount}</AppText></View></Card></>} ListEmptyComponent={<EmptyState icon="timeline" title="No activity yet" body="Stock movements and approved administration changes will appear here." />} /></ScreenContainer>;
}
const styles = StyleSheet.create({ list: { gap: 10, paddingBottom: 28 }, search: { height: 48, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.paper, borderRadius: 14, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 8 }, searchInput: { flex: 1, color: palette.ink, fontSize: 15, paddingVertical: 0 }, chart: { flexDirection: "row", gap: 18 }, barBackground: { height: 8, borderRadius: 4, backgroundColor: palette.subtle, overflow: "hidden" }, bar: { height: 8, borderRadius: 4 }, log: { flexDirection: "row", alignItems: "flex-start", gap: 10 }, logIcon: { width: 40, height: 40, borderRadius: 12, alignItems: "center", justifyContent: "center" } });
