import { useState } from "react";
import { Alert, FlatList, Modal, Pressable, StyleSheet, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { AppIcon, AppText, Card, EmptyState, Field, IconButton, PrimaryButton, ScreenTitle, palette } from "@/src/components/ui";
import { can } from "@/src/lib/permissions";
import { createCategoryLocally, deleteCategoryLocally } from "@/src/data/sync/mutations";
import { useRole, useStockTrack } from "@/src/providers/stocktrack-provider";
import type { Category } from "@/src/lib/types";

const colorOptions = [palette.indigo, palette.green, palette.amber, palette.purple, palette.blue, palette.red, palette.teal, "#C4528C"];
const iconOptions = ["inventory-2", "devices", "edit", "chair", "cleaning-services", "restaurant", "build", "medical-services", "checkroom", "sports-soccer"] as const;

export default function CategoriesScreen() {
  const { activeStore, data, user, refreshLocal } = useStockTrack(); const role = useRole(); const [modal, setModal] = useState(false); const [name, setName] = useState(""); const [color, setColor] = useState(colorOptions[0]); const [icon, setIcon] = useState<(typeof iconOptions)[number]>(iconOptions[0]); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const create = async () => { if (!activeStore || !user || !role) return; if (!name.trim()) return setError("Category name is required."); setBusy(true); setError(null); try { await createCategoryLocally(activeStore.id, { id: user.id, name: String(user.user_metadata.full_name ?? user.email ?? "You"), role }, name, color, icon); await refreshLocal(); setName(""); setModal(false); } catch (categoryError) { setError(categoryError instanceof Error ? categoryError.message : "Category could not be created."); } finally { setBusy(false); } };
  const remove = (category: Category) => { if (!activeStore || !user || role !== "owner") return; const general = data.categories.find((item) => item.name === "General"); if (!general) return Alert.alert("General category required", "Refresh this store before deleting a category."); Alert.alert(`Delete ${category.name}?`, `Items in this category will move to ${general.name}.`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => { void deleteCategoryLocally(category, general, { id: user.id, name: String(user.user_metadata.full_name ?? user.email ?? "You"), role: "owner" }).then(refreshLocal).catch((deleteError) => Alert.alert("Could not delete category", deleteError instanceof Error ? deleteError.message : "Try again.")); } }]); };
  const categoryRows = data.categories.map((category) => ({ ...category, count: data.items.filter((item) => item.categoryId === category.id || item.categoryName === category.name).length }));
  return <ScreenContainer className="p-4"><FlatList data={categoryRows} numColumns={2} columnWrapperStyle={categoryRows.length ? styles.columns : undefined} keyExtractor={(category) => category.id} contentContainerStyle={styles.list} ListHeaderComponent={<><ScreenTitle title="Categories" subtitle={activeStore ? `${activeStore.name} · ${categoryRows.length} categories` : "Choose a store"} action={can(role, "createCategories") ? <IconButton icon="add" label="Add category" onPress={() => setModal(true)} /> : undefined} />{!can(role, "createCategories") ? <Card><AppText size={13} color={palette.slate}>You can view category groups. Ask a manager to create or edit categories.</AppText></Card> : null}</>} renderItem={({ item }) => <Card style={styles.categoryCard}><View style={[styles.categoryIcon, { backgroundColor: `${item.colorValue}18` }]}><AppIcon name={item.iconCode as "inventory-2"} size={25} color={item.colorValue} /></View><AppText size={15} weight="700" numberOfLines={1}>{item.name}</AppText><AppText size={12} color={palette.slate}>{item.count} item{item.count === 1 ? "" : "s"}</AppText>{role === "owner" && item.name !== "General" ? <Pressable accessibilityRole="button" accessibilityLabel={`Delete ${item.name}`} onPress={() => remove(item)} style={({ pressed }) => [styles.delete, pressed && { opacity: 0.6 }]}><AppIcon name="delete-outline" size={18} color={palette.red} /></Pressable> : null}</Card>} ListEmptyComponent={<EmptyState icon="category" title="No categories yet" body="Categories make stock easier to find and count." />} />
    <Modal visible={modal} transparent animationType="slide" onRequestClose={() => setModal(false)}><View style={styles.overlay}><View style={styles.modal}><ScreenTitle title="Add category" action={<IconButton icon="close" label="Close" onPress={() => setModal(false)} />} /><Field label="Category name" value={name} onChangeText={setName} placeholder="e.g. Stationery" error={error ?? undefined} autoCapitalize="words" /><AppText size={13} weight="600" color={palette.slate}>Colour</AppText><View style={styles.optionRow}>{colorOptions.map((value) => <Pressable key={value} accessibilityRole="button" accessibilityLabel={`Select colour ${value}`} accessibilityState={{ selected: color === value }} onPress={() => setColor(value)} style={[styles.color, { backgroundColor: value }, color === value && styles.selected]} />)}</View><AppText size={13} weight="600" color={palette.slate}>Icon</AppText><View style={styles.optionRow}>{iconOptions.map((value) => <Pressable key={value} accessibilityRole="button" accessibilityLabel={`Select ${value} icon`} accessibilityState={{ selected: icon === value }} onPress={() => setIcon(value)} style={[styles.iconOption, icon === value && styles.iconSelected]}><AppIcon name={value} size={22} color={icon === value ? palette.paper : palette.indigo} /></Pressable>)}</View><PrimaryButton label="Create category" loading={busy} onPress={() => void create()} icon="add" /></View></View></Modal>
  </ScreenContainer>;
}
const styles = StyleSheet.create({ list: { gap: 12, paddingBottom: 30 }, columns: { gap: 12 }, categoryCard: { flex: 1, minHeight: 158, position: "relative", justifyContent: "flex-end" }, categoryIcon: { width: 48, height: 48, borderRadius: 15, justifyContent: "center", alignItems: "center", marginBottom: "auto" }, delete: { position: "absolute", top: 12, right: 10, padding: 4 }, overlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(23,32,51,0.38)" }, modal: { backgroundColor: palette.background, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, gap: 13 }, optionRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, color: { width: 32, height: 32, borderRadius: 16 }, selected: { borderWidth: 3, borderColor: palette.paper, outlineWidth: 2, outlineColor: palette.ink }, iconOption: { width: 40, height: 40, borderRadius: 12, borderWidth: 1, borderColor: "#C7D2FE", alignItems: "center", justifyContent: "center", backgroundColor: palette.paper }, iconSelected: { backgroundColor: palette.indigo, borderColor: palette.indigo } });
