import { useEffect, useState } from "react";
import { ScrollView, StyleSheet, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { AppIcon, AppText, Card, EmptyState, Field, PrimaryButton, ScreenTitle, SectionLabel, palette } from "@/src/components/ui";
import { renameStoreLocally } from "@/src/data/sync/mutations";
import { useRole, useStockTrack } from "@/src/providers/stocktrack-provider";

const scales = [{ label: "Small", value: 0.9 }, { label: "Default", value: 1 }, { label: "Medium", value: 1.1 }, { label: "Large", value: 1.2 }, { label: "Extra large", value: 1.25 }];
export default function SettingsScreen() { const { activeStore, user, fontScale, setFontScale, refreshLocal } = useStockTrack(); const role = useRole(); const [name, setName] = useState(activeStore?.name ?? ""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); useEffect(() => setName(activeStore?.name ?? ""), [activeStore?.name]); if (role !== "owner" || !activeStore || !user) return <ScreenContainer className="p-5"><EmptyState icon="lock" title="Owner access only" body="Store configuration is available to the owner." /></ScreenContainer>;
  const saveName = async () => { if (name.trim().length < 2) return setError("Store name must contain at least two characters."); setSaving(true); setError(null); try { await renameStoreLocally(activeStore, name); await refreshLocal(); } catch (renameError) { setError(renameError instanceof Error ? renameError.message : "Store name could not be updated."); } finally { setSaving(false); } };
  return <ScreenContainer className="p-4"><ScrollView contentContainerStyle={styles.content}><ScreenTitle title="Settings" subtitle={activeStore.name} /><SectionLabel>Store details</SectionLabel><Card><View style={styles.cardTitle}><View style={styles.symbol}><AppIcon name="storefront" color={palette.indigo} /></View><View><AppText size={16} weight="700">Store name</AppText><AppText size={12} color={palette.slate}>Visible to every collaborator</AppText></View></View><Field label="Store name" value={name} onChangeText={setName} error={error ?? undefined} autoCapitalize="words" /><PrimaryButton label="Save store name" loading={saving} icon="save" onPress={() => void saveName()} /></Card><SectionLabel>Appearance</SectionLabel><Card><AppText size={16} weight="700">Text size</AppText><AppText size={13} color={palette.slate}>This setting is saved on this device and applies throughout StockTrack.</AppText><View style={styles.scaleList}>{scales.map((option) => <PrimaryButton key={option.value} label={`${option.label} · ${Math.round(option.value * 100)}%`} secondary={fontScale !== option.value} onPress={() => void setFontScale(option.value)} />)}</View><View style={styles.preview}><AppText size={18} weight="700">Inventory at a glance</AppText><AppText size={14} color={palette.slate}>Preview the text size before returning to your inventory.</AppText></View></Card><SectionLabel>Collaboration</SectionLabel><Card><AppText size={16} weight="700">{activeStore.name} team</AppText><AppText size={13} color={palette.slate}>Manage invitations and access on the Team tab.</AppText></Card></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { gap: 12, paddingBottom: 28 }, cardTitle: { flexDirection: "row", alignItems: "center", gap: 10 }, symbol: { width: 42, height: 42, borderRadius: 13, backgroundColor: "#E9EFFF", alignItems: "center", justifyContent: "center" }, scaleList: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, preview: { backgroundColor: palette.subtle, borderRadius: 13, padding: 13, gap: 2 } });
