import { useState } from "react";
import { Alert, FlatList, Modal, StyleSheet, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { AppText, Card, EmptyState, Field, IconButton, PrimaryButton, ScreenTitle, palette } from "@/src/components/ui";
import { inviteMemberLocally, updateMemberLocally } from "@/src/data/sync/mutations";
import { useRole, useStockTrack } from "@/src/providers/stocktrack-provider";
import type { StoreMembership } from "@/src/lib/types";

export default function TeamScreen() {
  const { activeStore, data, user, refreshLocal } = useStockTrack(); const role = useRole(); const [modal, setModal] = useState(false); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [inviteRole, setInviteRole] = useState<"staff" | "manager">("staff"); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  if (role !== "owner" || !activeStore || !user) return <ScreenContainer className="p-5"><EmptyState icon="lock" title="Owner access only" body="Only the store owner can invite people or change their access." /></ScreenContainer>;
  const actor = { id: user.id, name: String(user.user_metadata.full_name ?? user.email ?? "You"), role: "owner" as const };
  const invite = async () => { if (name.trim().length < 2) return setError("Enter the collaborator’s full name."); if (!email.includes("@")) return setError("Enter a valid email address."); setBusy(true); setError(null); try { await inviteMemberLocally(activeStore.id, actor, name, email, inviteRole); await refreshLocal(); setName(""); setEmail(""); setModal(false); } catch (inviteError) { setError(inviteError instanceof Error ? inviteError.message : "Invitation could not be prepared."); } finally { setBusy(false); } };
  const change = (member: StoreMembership, update: Parameters<typeof updateMemberLocally>[2], title: string, message: string) => Alert.alert(title, message, [{ text: "Cancel", style: "cancel" }, { text: "Confirm", style: update.remove ? "destructive" : "default", onPress: () => { void updateMemberLocally(member, actor, update).then(refreshLocal).catch((changeError) => Alert.alert("Could not update access", changeError instanceof Error ? changeError.message : "Try again.")); } }]);
  return <ScreenContainer className="p-4"><FlatList data={data.members} keyExtractor={(member) => member.id} contentContainerStyle={styles.list} ListHeaderComponent={<ScreenTitle title="Team" subtitle={`${activeStore.name} · ${data.members.length} member${data.members.length === 1 ? "" : "s"}`} action={<IconButton icon="person-add" label="Invite collaborator" onPress={() => setModal(true)} />} />} renderItem={({ item }) => <Card><View style={styles.member}><View style={[styles.avatar, { backgroundColor: item.role === "owner" ? "#E9EFFF" : item.role === "manager" ? "#E8F6F1" : "#F0F2F5" }]}><AppText size={16} weight="700" color={item.role === "owner" ? palette.indigo : item.role === "manager" ? palette.green : palette.slate}>{(item.fullName ?? item.email ?? "?").slice(0, 1).toUpperCase()}</AppText></View><View style={{ flex: 1, gap: 1 }}><AppText size={15} weight="700">{item.fullName ?? "Team member"}</AppText><AppText size={12} color={palette.slate}>{item.email ?? "Account linked to this store"}</AppText></View><View style={[styles.badge, { backgroundColor: item.isActive ? "#E9F7F0" : "#FDECEC" }]}><AppText size={11} weight="700" color={item.isActive ? palette.green : palette.red}>{item.isActive ? item.role : "Disabled"}</AppText></View></View>{item.role !== "owner" ? <View style={styles.memberActions}><PrimaryButton label={item.role === "manager" ? "Make staff" : "Make manager"} secondary onPress={() => change(item, { role: item.role === "manager" ? "staff" : "manager" }, "Change role?", `This person will become ${item.role === "manager" ? "Staff" : "Manager"}.`)} /><PrimaryButton label={item.isActive ? "Disable" : "Enable"} secondary onPress={() => change(item, { isActive: !item.isActive }, item.isActive ? "Disable access?" : "Enable access?", item.isActive ? "They will immediately lose access when online." : "They can access this store again.")} /><PrimaryButton label="Remove" secondary onPress={() => change(item, { remove: true }, "Remove collaborator?", "This removes their access to this store.")} /></View> : null}</Card>} ListEmptyComponent={<EmptyState icon="group" title="No collaborators yet" body="Invite a manager or staff member to count stock together." />} />
    <Modal visible={modal} transparent animationType="slide" onRequestClose={() => setModal(false)}><View style={styles.overlay}><View style={styles.modal}><ScreenTitle title="Invite collaborator" action={<IconButton icon="close" label="Close" onPress={() => setModal(false)} />} /><AppText size={13} color={palette.slate}>Existing accounts join immediately. New accounts are saved as a pending invitation until the email workflow is enabled.</AppText><Field label="Full name" value={name} onChangeText={setName} placeholder="Taylor Rivers" autoCapitalize="words" /><Field label="Email address" value={email} onChangeText={setEmail} placeholder="taylor@company.com" autoCapitalize="none" keyboardType="email-address" error={error ?? undefined} /><View style={styles.roleChoice}><View style={{ flex: 1 }}><PrimaryButton label="Staff" secondary={inviteRole !== "staff"} onPress={() => setInviteRole("staff")} /></View><View style={{ flex: 1 }}><PrimaryButton label="Manager" secondary={inviteRole !== "manager"} onPress={() => setInviteRole("manager")} /></View></View><PrimaryButton label="Prepare invitation" icon="send" loading={busy} onPress={() => void invite()} /></View></View></Modal>
  </ScreenContainer>;
}
const styles = StyleSheet.create({ list: { gap: 11, paddingBottom: 28 }, member: { flexDirection: "row", alignItems: "center", gap: 10 }, avatar: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, badge: { paddingHorizontal: 8, minHeight: 24, borderRadius: 12, justifyContent: "center" }, memberActions: { flexDirection: "row", gap: 7, flexWrap: "wrap", borderTopWidth: 1, borderTopColor: "#F0F2F5", paddingTop: 10 }, overlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(23,32,51,0.38)" }, modal: { backgroundColor: palette.background, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, gap: 13 }, roleChoice: { flexDirection: "row", gap: 10 } });
